# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485b1fc63f4eb1d34c5357053267ca20c91d2507c4387c5a69e782cbdc14dd43f991fd1ed92a6347d1d75e5412c24bcab603e76a315677d39b519a77d10d8b5a

test:
  secret_key_base: 5f25d19f974cb8d87b2401f7a350131a52d27696e933db553ac197676b99aa470e4383eb5691e823be3d1844826611414507fb0c78744f17674a7beb8d22be26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
